version: '3.8'

services:
  nodejs:
    build: .
    networks:
      - nodnet
    volumes:  # Fixed 'volumes'
      - ~/backend/rccg:/usr/app
      - /usr/app/node_modules
    ports: 
      - 3000:3000
    restart: always

volumes:
  node-data:
    driver: local 
networks:
  nodnet:
    driver: bridge